begin;

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists private.admin_emails (
  email text primary key check (email = lower(email) and char_length(email) between 5 and 254),
  created_at timestamptz not null default now()
);
alter table private.admin_emails enable row level security;
revoke all on private.admin_emails from public, anon, authenticated;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id smallint primary key default 1 check (id = 1),
  brand text not null check (char_length(brand) between 1 and 80),
  hero_title text not null check (char_length(hero_title) between 1 and 180),
  hero_subtitle text not null check (char_length(hero_subtitle) between 1 and 500),
  whatsapp text not null check (whatsapp ~ '^[0-9]{10,15}$'),
  customer_count text not null check (char_length(customer_count) between 1 and 24),
  rating_value numeric(2,1) not null check (rating_value between 0 and 5),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('servico', 'produto')),
  icon text not null default '◆' check (char_length(icon) between 1 and 12),
  name text not null check (char_length(name) between 1 and 120),
  description text not null check (char_length(description) between 1 and 800),
  price numeric(12,2) not null check (price >= 0),
  image_path text check (image_path is null or char_length(image_path) <= 500),
  active boolean not null default true,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 80),
  rating smallint not null check (rating between 1 and 5),
  message text not null check (char_length(btrim(message)) between 3 and 2500),
  status text not null default 'pending' check (status in ('pending', 'published', 'archived')),
  created_at timestamptz not null default now()
);

create index if not exists catalog_items_public_order_idx
  on public.catalog_items (active, position, id);
create index if not exists feedbacks_status_created_idx
  on public.feedbacks (status, created_at desc);

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    exists (
      select 1
      from public.admin_users
      where user_id = (select auth.uid())
    )
    or exists (
      select 1
      from auth.users as users
      join private.admin_emails as allowed
        on allowed.email = lower(users.email)
      where users.id = (select auth.uid())
    );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select private.is_admin();
$$;

revoke all on function public.current_user_is_admin() from public, anon;
grant execute on function public.current_user_is_admin() to authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function private.set_updated_at();

drop trigger if exists catalog_items_set_updated_at on public.catalog_items;
create trigger catalog_items_set_updated_at
before update on public.catalog_items
for each row execute function private.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.catalog_items enable row level security;
alter table public.feedbacks enable row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.site_settings from anon, authenticated;
revoke all on public.catalog_items from anon, authenticated;
revoke all on public.feedbacks from anon, authenticated;

grant select on public.site_settings to anon, authenticated;
grant update on public.site_settings to authenticated;

grant select on public.catalog_items to anon, authenticated;
grant insert, update, delete on public.catalog_items to authenticated;
grant usage, select on sequence public.catalog_items_id_seq to authenticated;

grant insert on public.feedbacks to anon;
grant select, insert, update, delete on public.feedbacks to authenticated;
grant usage, select on sequence public.feedbacks_id_seq to anon, authenticated;

drop policy if exists "sos_settings_public_read" on public.site_settings;
create policy "sos_settings_public_read"
on public.site_settings for select
to anon, authenticated
using (id = 1);

drop policy if exists "sos_settings_admin_update" on public.site_settings;
create policy "sos_settings_admin_update"
on public.site_settings for update
to authenticated
using ((select private.is_admin()))
with check (id = 1 and (select private.is_admin()));

drop policy if exists "sos_catalog_public_read" on public.catalog_items;
create policy "sos_catalog_public_read"
on public.catalog_items for select
to anon
using (active);

drop policy if exists "sos_catalog_authenticated_read" on public.catalog_items;
create policy "sos_catalog_authenticated_read"
on public.catalog_items for select
to authenticated
using (active or (select private.is_admin()));

drop policy if exists "sos_catalog_admin_insert" on public.catalog_items;
create policy "sos_catalog_admin_insert"
on public.catalog_items for insert
to authenticated
with check ((select private.is_admin()));

drop policy if exists "sos_catalog_admin_update" on public.catalog_items;
create policy "sos_catalog_admin_update"
on public.catalog_items for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "sos_catalog_admin_delete" on public.catalog_items;
create policy "sos_catalog_admin_delete"
on public.catalog_items for delete
to authenticated
using ((select private.is_admin()));

drop policy if exists "sos_feedback_public_insert" on public.feedbacks;
create policy "sos_feedback_public_insert"
on public.feedbacks for insert
to anon
with check (
  status = 'pending'
  and char_length(btrim(name)) between 2 and 80
  and char_length(btrim(message)) between 3 and 2500
  and rating between 1 and 5
);

drop policy if exists "sos_feedback_admin_all" on public.feedbacks;
create policy "sos_feedback_admin_all"
on public.feedbacks for all
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

insert into public.site_settings (
  id, brand, hero_title, hero_subtitle, whatsapp, customer_count, rating_value
)
values (
  1,
  'S.O.S Filtros',
  'Soluções que cuidam do seu equipamento e da sua tranquilidade.',
  'Serviços especializados e produtos de qualidade para manter tudo funcionando com segurança, eficiência e confiança.',
  '5511999999999',
  '1.500',
  4.9
)
on conflict (id) do nothing;

insert into public.catalog_items (type, icon, name, description, price, position)
select seed.type, seed.icon, seed.name, seed.description, seed.price, seed.position
from (
  values
    ('servico', '✦', 'Identidade Visual', 'Criação de uma marca completa, moderna e memorável para o seu negócio.', 1290.00, 10),
    ('servico', '◈', 'Site Profissional', 'Site responsivo e estratégico para apresentar sua empresa e gerar oportunidades.', 2490.00, 20),
    ('servico', '↗', 'Consultoria Digital', 'Diagnóstico e plano de ação para acelerar seus resultados no ambiente digital.', 690.00, 30),
    ('produto', '▣', 'Kit Social Media', 'Templates editáveis para deixar suas redes sociais mais profissionais.', 149.90, 40),
    ('produto', '◆', 'Manual de Marca', 'Guia prático para aplicar sua identidade de forma consistente.', 89.90, 50),
    ('produto', '⚡', 'Pack Produtividade', 'Planilhas e ferramentas para organizar projetos, clientes e finanças.', 59.90, 60)
) as seed(type, icon, name, description, price, position)
where not exists (select 1 from public.catalog_items);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'catalogo',
  'catalogo',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "sos_catalog_images_public_read" on storage.objects;
create policy "sos_catalog_images_public_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'catalogo');

drop policy if exists "sos_catalog_images_admin_insert" on storage.objects;
create policy "sos_catalog_images_admin_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'catalogo' and (select private.is_admin()));

drop policy if exists "sos_catalog_images_admin_update" on storage.objects;
create policy "sos_catalog_images_admin_update"
on storage.objects for update
to authenticated
using (bucket_id = 'catalogo' and (select private.is_admin()))
with check (bucket_id = 'catalogo' and (select private.is_admin()));

drop policy if exists "sos_catalog_images_admin_delete" on storage.objects;
create policy "sos_catalog_images_admin_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'catalogo' and (select private.is_admin()));

commit;
