const defaults={brand:'Nexo Prime',title:'Soluções que transformam ideias em resultados.',subtitle:'Serviços especializados e produtos selecionados para tornar seu próximo projeto mais simples, rápido e marcante.',whatsapp:'5511999999999',items:[{id:1,type:'servico',icon:'✦',name:'Identidade Visual',description:'Criação de uma marca completa, moderna e memorável para o seu negócio.',price:1290},{id:2,type:'servico',icon:'◈',name:'Site Profissional',description:'Site responsivo e estratégico para apresentar sua empresa e gerar oportunidades.',price:2490},{id:3,type:'servico',icon:'↗',name:'Consultoria Digital',description:'Diagnóstico e plano de ação para acelerar seus resultados no ambiente digital.',price:690},{id:4,type:'produto',icon:'▣',name:'Kit Social Media',description:'Templates editáveis para deixar suas redes sociais mais profissionais.',price:149.9},{id:5,type:'produto',icon:'◆',name:'Manual de Marca',description:'Guia prático para aplicar sua identidade de forma consistente.',price:89.9},{id:6,type:'produto',icon:'⚡',name:'Pack Produtividade',description:'Planilhas e ferramentas para organizar projetos, clientes e finanças.',price:59.9}],portfolio:[{name:'Aurora Studio',category:'Identidade Visual'},{name:'Vértice Consultoria',category:'Website & Estratégia'},{name:'Move Fitness',category:'Campanha Digital'}]};
const storageKey='sosFiltrosData';let data=JSON.parse(localStorage.getItem(storageKey)||'null')||structuredClone(defaults);if(data.brand==='Nexo Prime'){data.brand='S.O.S Filtros';data.title='Soluções que cuidam do seu equipamento e da sua tranquilidade.';data.subtitle='Serviços especializados e produtos de qualidade para manter tudo funcionando com segurança, eficiência e confiança.'}data.customerCount??='1.500';data.ratingValue??='4.9';data.feedbacks??=[];let cart=[];let currentFilter='todos';
const $=s=>document.querySelector(s);const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const save=()=>localStorage.setItem(storageKey,JSON.stringify(data));
function renderGeneral(){brandName.textContent=footerBrand.textContent=data.brand;heroTitle.textContent=data.title;heroSubtitle.textContent=data.subtitle;document.getElementById('customerCount').textContent=`+${data.customerCount}`;document.getElementById('ratingValue').textContent=data.ratingValue;whatsappLink.href=`https://wa.me/${data.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de saber mais sobre seus serviços e produtos.')}`;document.title=`${data.brand} | Serviços e Produtos`}
function renderCatalog(){const visible=data.items.filter(i=>currentFilter==='todos'||i.type===currentFilter);catalogGrid.innerHTML=visible.map(i=>{const name=escapeHtml(i.name),description=escapeHtml(i.description),type=i.type==='produto'?'produto':'servico',icon=escapeHtml(i.icon),image=typeof i.image==='string'&&/^data:image\/(png|jpeg|webp|gif);base64,/i.test(i.image)?i.image:'';return `<article class="catalog-card reveal"><div class="card-visual ${type}">${image?`<img class="item-image" src="${image}" alt="${name}">`:`<span class="card-icon">${icon}</span>`}<span class="type-tag">${type}</span></div><div class="card-content"><h3>${name}</h3><p>${description}</p><div class="card-bottom"><span class="price">${money(Number(i.price)||0)}</span><button class="add-button" data-add="${Number(i.id)}" aria-label="Adicionar ${name}">+</button></div></div></article>`}).join('')||'<p>Nenhum item nesta categoria.</p>'}
function renderCart(){cartCount.textContent=cart.length;cartItems.innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-item"><div><h4>${escapeHtml(i.name)}</h4><small>${i.type==='servico'?'Contratação':'Produto'} · ${money(Number(i.price)||0)}</small></div><button class="remove" data-remove="${n}">Remover</button></div>`).join(''):'<div class="cart-empty">Seu carrinho está vazio.<br>Explore o catálogo para começar.</div>';cartTotal.textContent=money(cart.reduce((s,i)=>s+(Number(i.price)||0),0))}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2500)}
function openCart(){cartDrawer.classList.add('open');drawerBackdrop.classList.add('open')};function closeCart(){cartDrawer.classList.remove('open');drawerBackdrop.classList.remove('open')}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderCatalog()});
catalogGrid.onclick=e=>{const id=Number(e.target.dataset.add);if(id){cart.push(data.items.find(i=>i.id===id));renderCart();toast('Item adicionado ao carrinho')}};
cartItems.onclick=e=>{if(e.target.dataset.remove!==undefined){cart.splice(Number(e.target.dataset.remove),1);renderCart()}};
document.getElementById('openCart').onclick=openCart;drawerBackdrop.onclick=closeCart;document.querySelector('[data-close="cart"]').onclick=closeCart;
menuToggle.onclick=()=>{mainNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',mainNav.classList.contains('open'))};mainNav.querySelectorAll('a').forEach(a=>a.onclick=()=>mainNav.classList.remove('open'));
contactForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const text=`Olá! Sou ${f.get('name')}.%0A%0A${f.get('subject')}%0A${f.get('message')}%0A%0AE-mail: ${f.get('email')}`;formStatus.textContent='Abrindo uma conversa no WhatsApp…';window.open(`https://wa.me/${data.whatsapp}?text=${text}`,'_blank')};
checkoutButton.onclick=()=>{if(!cart.length)return toast('Adicione um item antes de finalizar');closeCart();checkoutDialog.showModal()};checkoutForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),summary=cart.map(i=>`• ${i.name} — ${money(i.price)}`).join('%0A'),total=money(cart.reduce((s,i)=>s+i.price,0));window.open(`https://wa.me/${data.whatsapp}?text=${encodeURIComponent(`Olá! Sou ${f.get('name')} e quero confirmar este pedido:`)}%0A%0A${summary}%0A%0ATotal: ${encodeURIComponent(total)}%0APagamento: ${f.get('payment')}`,'_blank');checkoutDialog.close();cart=[];renderCart();toast('Pedido preparado com sucesso!')};
let selectedRating=0;document.querySelectorAll('#feedbackStars button').forEach(button=>button.onclick=()=>{selectedRating=Number(button.dataset.star);document.querySelectorAll('#feedbackStars button').forEach(star=>star.classList.toggle('selected',Number(star.dataset.star)<=selectedRating))});feedbackForm.onsubmit=e=>{e.preventDefault();if(!selectedRating){feedbackStatus.textContent='Escolha de 1 a 5 estrelas.';return}const form=new FormData(e.target);data.feedbacks.unshift({id:Date.now(),name:form.get('name'),rating:selectedRating,message:form.get('message'),date:new Date().toLocaleDateString('pt-BR')});save();e.target.reset();selectedRating=0;document.querySelectorAll('#feedbackStars button').forEach(star=>star.classList.remove('selected'));feedbackStatus.textContent='Obrigado! Sua avaliação foi enviada.'};
const toastEl=$('#toast');year.textContent=new Date().getFullYear();save();renderGeneral();renderCatalog();renderCart();
